export interface Country {
  name: string;
  code: string;
  callingCode: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: 'India', code: 'IN', callingCode: '+91', flag: '🇮🇳' },
  { name: 'United States', code: 'US', callingCode: '+1', flag: '🇺🇸' },
  { name: 'United Kingdom', code: 'GB', callingCode: '+44', flag: '🇬🇧' },
  { name: 'Canada', code: 'CA', callingCode: '+1', flag: '🇨🇦' },
  { name: 'Australia', code: 'AU', callingCode: '+61', flag: '🇦🇺' },
  { name: 'Germany', code: 'DE', callingCode: '+49', flag: '🇩🇪' },
  { name: 'France', code: 'FR', callingCode: '+33', flag: '🇫🇷' },
  { name: 'Japan', code: 'JP', callingCode: '+81', flag: '🇯🇵' },
  { name: 'Singapore', code: 'SG', callingCode: '+65', flag: '🇸🇬' },
  { name: 'United Arab Emirates', code: 'AE', callingCode: '+971', flag: '🇦🇪' },
  { name: 'Afghanistan', code: 'AF', callingCode: '+93', flag: '🇦🇫' },
  { name: 'Albania', code: 'AL', callingCode: '+355', flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', callingCode: '+213', flag: '🇩🇿' },
  { name: 'Andorra', code: 'AD', callingCode: '+376', flag: '🇦🇩' },
  { name: 'Angola', code: 'AO', callingCode: '+244', flag: '🇦🇴' },
  { name: 'Argentina', code: 'AR', callingCode: '+54', flag: '🇦🇷' },
  { name: 'Armenia', code: 'AM', callingCode: '+374', flag: '🇦🇲' },
  { name: 'Austria', code: 'AT', callingCode: '+43', flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', callingCode: '+994', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', callingCode: '+1-242', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', callingCode: '+973', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', callingCode: '+880', flag: '🇧🇩' },
  { name: 'Barbados', code: 'BB', callingCode: '+1-246', flag: '🇧🇧' },
  { name: 'Belarus', code: 'BY', callingCode: '+375', flag: '🇧🇾' },
  { name: 'Belgium', code: 'BE', callingCode: '+32', flag: '🇧🇪' },
  { name: 'Belize', code: 'BZ', callingCode: '+501', flag: '🇧🇿' },
  { name: 'Benin', code: 'BJ', callingCode: '+229', flag: '🇧🇯' },
  { name: 'Bhutan', code: 'BT', callingCode: '+975', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'BO', callingCode: '+591', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'BA', callingCode: '+387', flag: '🇧🇦' },
  { name: 'Botswana', code: 'BW', callingCode: '+267', flag: '🇧🇼' },
  { name: 'Brazil', code: 'BR', callingCode: '+55', flag: '🇧🇷' },
  { name: 'Brunei', code: 'BN', callingCode: '+673', flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'BG', callingCode: '+359', flag: '🇧🇬' },
  { name: 'Cambodia', code: 'KH', callingCode: '+855', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', callingCode: '+237', flag: '🇨🇲' },
  { name: 'Chile', code: 'CL', callingCode: '+56', flag: '🇨🇱' },
  { name: 'China', code: 'CN', callingCode: '+86', flag: '🇨🇳' },
  { name: 'Colombia', code: 'CO', callingCode: '+57', flag: '🇨🇴' },
  { name: 'Costa Rica', code: 'CR', callingCode: '+506', flag: '🇨🇷' },
  { name: 'Croatia', code: 'HR', callingCode: '+385', flag: '🇭🇷' },
  { name: 'Cyprus', code: 'CY', callingCode: '+357', flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', callingCode: '+420', flag: '🇨🇿' },
  { name: 'Denmark', code: 'DK', callingCode: '+45', flag: '🇩🇰' },
  { name: 'Dominican Republic', code: 'DO', callingCode: '+1-809', flag: '🇩🇴' },
  { name: 'Ecuador', code: 'EC', callingCode: '+593', flag: '🇪🇨' },
  { name: 'Egypt', code: 'EG', callingCode: '+20', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', callingCode: '+503', flag: '🇸🇻' },
  { name: 'Estonia', code: 'EE', callingCode: '+372', flag: '🇪🇪' },
  { name: 'Ethiopia', code: 'ET', callingCode: '+251', flag: '🇪🇹' },
  { name: 'Fiji', code: 'FJ', callingCode: '+679', flag: '🇫🇯' },
  { name: 'Finland', code: 'FI', callingCode: '+358', flag: '🇫🇮' },
  { name: 'Georgia', code: 'GE', callingCode: '+995', flag: '🇬🇪' },
  { name: 'Ghana', code: 'GH', callingCode: '+233', flag: '🇬🇭' },
  { name: 'Greece', code: 'GR', callingCode: '+30', flag: '🇬🇷' },
  { name: 'Guatemala', code: 'GT', callingCode: '+502', flag: '🇬🇹' },
  { name: 'Honduras', code: 'HN', callingCode: '+504', flag: '🇭🇳' },
  { name: 'Hong Kong', code: 'HK', callingCode: '+852', flag: '🇭🇰' },
  { name: 'Hungary', code: 'HU', callingCode: '+36', flag: '🇭🇺' },
  { name: 'Iceland', code: 'IS', callingCode: '+354', flag: '🇮🇸' },
  { name: 'Indonesia', code: 'ID', callingCode: '+62', flag: '🇮🇩' },
  { name: 'Iran', code: 'IR', callingCode: '+98', flag: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', callingCode: '+964', flag: '🇮🇶' },
  { name: 'Ireland', code: 'IE', callingCode: '+353', flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', callingCode: '+972', flag: '🇮🇱' },
  { name: 'Italy', code: 'IT', callingCode: '+39', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', callingCode: '+1-876', flag: '🇯🇲' },
  { name: 'Jordan', code: 'JO', callingCode: '+962', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', callingCode: '+7', flag: '🇰🇿' },
  { name: 'Kenya', code: 'KE', callingCode: '+254', flag: '🇰🇪' },
  { name: 'Kuwait', code: 'KW', callingCode: '+965', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', callingCode: '+996', flag: '🇰🇬' },
  { name: 'Laos', code: 'LA', callingCode: '+856', flag: '🇱🇦' },
  { name: 'Latvia', code: 'LV', callingCode: '+371', flag: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', callingCode: '+961', flag: '🇱🇧' },
  { name: 'Libya', code: 'LY', callingCode: '+218', flag: '🇱🇾' },
  { name: 'Lithuania', code: 'LT', callingCode: '+370', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', callingCode: '+352', flag: '🇱🇺' },
  { name: 'Macau', code: 'MO', callingCode: '+853', flag: '🇲🇴' },
  { name: 'Malaysia', code: 'MY', callingCode: '+60', flag: '🇲🇾' },
  { name: 'Maldives', code: 'MV', callingCode: '+960', flag: '🇲🇻' },
  { name: 'Malta', code: 'MT', callingCode: '+356', flag: '🇲🇹' },
  { name: 'Mauritius', code: 'MU', callingCode: '+230', flag: '🇲🇺' },
  { name: 'Mexico', code: 'MX', callingCode: '+52', flag: '🇲🇽' },
  { name: 'Moldova', code: 'MD', callingCode: '+373', flag: '🇲🇩' },
  { name: 'Monaco', code: 'MC', callingCode: '+377', flag: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', callingCode: '+976', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', callingCode: '+382', flag: '🇲🇪' },
  { name: 'Morocco', code: 'MA', callingCode: '+212', flag: '🇲🇦' },
  { name: 'Myanmar', code: 'MM', callingCode: '+95', flag: '🇲🇲' },
  { name: 'Nepal', code: 'NP', callingCode: '+977', flag: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', callingCode: '+31', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', callingCode: '+64', flag: '🇳🇿' },
  { name: 'Nigeria', code: 'NG', callingCode: '+234', flag: '🇳🇬' },
  { name: 'North Macedonia', code: 'MK', callingCode: '+389', flag: '🇲🇰' },
  { name: 'Norway', code: 'NO', callingCode: '+47', flag: '🇳🇴' },
  { name: 'Oman', code: 'OM', callingCode: '+968', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', callingCode: '+92', flag: '🇵🇰' },
  { name: 'Panama', code: 'PA', callingCode: '+507', flag: '🇵🇦' },
  { name: 'Paraguay', code: 'PY', callingCode: '+595', flag: '🇵🇾' },
  { name: 'Peru', code: 'PE', callingCode: '+51', flag: '🇵🇪' },
  { name: 'Philippines', code: 'PH', callingCode: '+63', flag: '🇵🇭' },
  { name: 'Poland', code: 'PL', callingCode: '+48', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', callingCode: '+351', flag: '🇵🇹' },
  { name: 'Qatar', code: 'QA', callingCode: '+974', flag: '🇶🇦' },
  { name: 'Romania', code: 'RO', callingCode: '+40', flag: '🇷🇴' },
  { name: 'Russia', code: 'RU', callingCode: '+7', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', callingCode: '+250', flag: '🇷🇼' },
  { name: 'Saudi Arabia', code: 'SA', callingCode: '+966', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SN', callingCode: '+221', flag: '🇸🇳' },
  { name: 'Serbia', code: 'RS', callingCode: '+381', flag: '🇷🇸' },
  { name: 'Slovakia', code: 'SK', callingCode: '+421', flag: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', callingCode: '+386', flag: '🇸🇮' },
  { name: 'South Africa', code: 'ZA', callingCode: '+27', flag: '🇿🇦' },
  { name: 'South Korea', code: 'KR', callingCode: '+82', flag: '🇰🇷' },
  { name: 'Spain', code: 'ES', callingCode: '+34', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', callingCode: '+94', flag: '🇱🇰' },
  { name: 'Sweden', code: 'SE', callingCode: '+46', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', callingCode: '+41', flag: '🇨🇭' },
  { name: 'Taiwan', code: 'TW', callingCode: '+886', flag: '🇹🇼' },
  { name: 'Tanzania', code: 'TZ', callingCode: '+255', flag: '🇹🇿' },
  { name: 'Thailand', code: 'TH', callingCode: '+66', flag: '🇹🇭' },
  { name: 'Tunisia', code: 'TN', callingCode: '+216', flag: '🇹🇳' },
  { name: 'Turkey', code: 'TR', callingCode: '+90', flag: '🇹🇷' },
  { name: 'Uganda', code: 'UG', callingCode: '+256', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', callingCode: '+380', flag: '🇺🇦' },
  { name: 'Uruguay', code: 'UY', callingCode: '+598', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', callingCode: '+998', flag: '🇺🇿' },
  { name: 'Venezuela', code: 'VE', callingCode: '+58', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', callingCode: '+84', flag: '🇻🇳' },
  { name: 'Zambia', code: 'ZM', callingCode: '+260', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', callingCode: '+263', flag: '🇿🇼' },
];
